<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c47fda8d-6897-4a4f-96ea-e7744ccd8663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/Content/images/logo.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f40a18fb-f063-4fb7-9a94-8fb45642957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Content/images/logo.svg</value>
      <webElementGuid>c0e90d78-1abf-4234-9467-8063bf9a5f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;container page-{page}&quot;]/div[@class=&quot;ssi_loginMain col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;ssi_login&quot;]/div[@class=&quot;ssi_loginScreenMain&quot;]/div[@class=&quot;header col-lg-12 col-md-12&quot;]/div[@class=&quot;logo&quot;]/img[1]</value>
      <webElementGuid>4e6ca52b-0209-48d9-abff-c353e0ba3d8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div/div/div/div/div/div/img</value>
      <webElementGuid>b6c9bcd3-9112-4d5e-ae9d-bfb0b248927f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>273c5af0-6bf9-4e30-aa44-bd28f8c1f39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Content/images/logo.svg']</value>
      <webElementGuid>9a6dc1cd-4e36-497e-ad3b-de5386ca48d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
