<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>operations</name>
   <tag></tag>
   <elementGuidId>f3270bfa-a27d-4680-8f90-25b61bc3c2b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slidemenu']/ul/li[2]/a/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;slidemenu&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;root-menu has-drop active&quot;]/a[@class=&quot;top-menu-icon&quot;]/span[@class=&quot;icon-holder&quot;]/span[@class=&quot;icon icon-operations&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon.icon-operations</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fe48466-53b4-40d3-8849-a2fe4afa0b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-operations</value>
      <webElementGuid>312e8b97-04ad-4a36-ba2e-d9d9e7bdcbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slidemenu&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;root-menu has-drop active&quot;]/a[@class=&quot;top-menu-icon&quot;]/span[@class=&quot;icon-holder&quot;]/span[@class=&quot;icon icon-operations&quot;]</value>
      <webElementGuid>2dae17a9-4a70-4634-808e-79ad8e0b39da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidemenu']/ul/li[2]/a/span/span</value>
      <webElementGuid>ecc3e7fc-d547-4631-a2b8-8328dfd10656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span/span</value>
      <webElementGuid>e54ca03f-362b-4bcd-ae49-b3a340f74a8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
