<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>2892c828-b57c-49d0-927e-9ae7897c5cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cancelAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cancelAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e6a0e635-3ca9-44f2-8b15-667578c3ed35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondaryBtn</value>
      <webElementGuid>0d25d625-ca0f-41e8-bc1f-41320214f78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>103fddc2-54f2-46de-b799-2477b3e8948d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelAction</value>
      <webElementGuid>85db9cc6-1987-437e-a168-0f22d8221826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>16881233-8af7-4f6a-b961-398cf463f842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addTimeLogActionEventHandler(event, this,{&quot;Id&quot;:&quot;cancelAction&quot;,&quot;DisplayText&quot;:&quot;Cancel&quot;,&quot;ToolTip&quot;:&quot;Cancel&quot;,&quot;ActionAddress&quot;:{&quot;ActionName&quot;:&quot;GetListView&quot;,&quot;ControllerName&quot;:&quot;EmployeeAttendance&quot;,&quot;AreaName&quot;:&quot;Talent.App.WebUI&quot;,&quot;Parameters&quot;:null,&quot;Url&quot;:&quot;/Talent.App.WebUI/EmployeeAttendance/GetListView&quot;},&quot;IsMainAction&quot;:true,&quot;Status&quot;:1})</value>
      <webElementGuid>2e3ff0ee-ce99-406f-8eaa-c438bd4c6c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel</value>
      <webElementGuid>a6a0e326-6549-4999-9ec0-b6d564fdfe3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelAction&quot;)</value>
      <webElementGuid>9fbc703e-2a51-45e9-9459-c01f63901a91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cancelAction']</value>
      <webElementGuid>46066989-64fb-4010-9dde-6fe991d4d528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterContent']/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>3ad4ddfb-db27-41fe-8c10-1ef0f890e905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>942eff46-b3c8-4284-8cc1-52ca32797f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Time Log'])[2]/following::a[2]</value>
      <webElementGuid>f5306e08-8697-4e4d-8c24-536ad90093ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[2]/following::a[2]</value>
      <webElementGuid>46b9c1b3-7bef-456e-be84-c18c91b96f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Log Approving Person:'])[1]/preceding::a[1]</value>
      <webElementGuid>d165b20f-23d3-4e60-aae0-3a662c6d2c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizwan Ul Ahmad Khan'])[1]/preceding::a[1]</value>
      <webElementGuid>66d5ab25-918b-40f6-a7cb-462e59601903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>ac01fbd6-317d-4c3a-833e-33f700904c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>d551dba7-da55-440d-93e0-f204b0458c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>75ded55a-32ad-4faa-a15c-10a8ec9ac8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'cancelAction' and @title = 'Cancel' and (text() = ' Cancel' or . = ' Cancel')]</value>
      <webElementGuid>a81bb314-bbe6-4bb7-bf2a-98984be551e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
