<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>874fe270-23fb-42b1-85db-7587b4d88972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cancelAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cancelAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c839d4a1-c17c-4f9a-abef-9a931fb460cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondaryBtn</value>
      <webElementGuid>23f6d1d3-517e-4b90-9a66-d3c7d79d4492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ade4ab6b-bcde-42fc-aeea-8c938ca26bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelAction</value>
      <webElementGuid>2797656c-65b6-4d90-af4b-f93e0e62c407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>462cd1d7-de82-4ea5-a6cc-d4714f0d43c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addTimeLogActionEventHandler(event, this,{&quot;Id&quot;:&quot;cancelAction&quot;,&quot;DisplayText&quot;:&quot;Cancel&quot;,&quot;ToolTip&quot;:&quot;Cancel&quot;,&quot;ActionAddress&quot;:{&quot;ActionName&quot;:&quot;GetListView&quot;,&quot;ControllerName&quot;:&quot;EmployeeAttendance&quot;,&quot;AreaName&quot;:&quot;Talent.App.WebUI&quot;,&quot;Parameters&quot;:null,&quot;Url&quot;:&quot;/Talent.App.WebUI/EmployeeAttendance/GetListView&quot;},&quot;IsMainAction&quot;:true,&quot;Status&quot;:1})</value>
      <webElementGuid>7ffa80ad-5224-440d-9c0e-a02a3b138e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel</value>
      <webElementGuid>2ca845a1-a4db-4436-9632-9bbfbc0a1155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelAction&quot;)</value>
      <webElementGuid>05894e8b-0f97-413b-9609-d5464f37110e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cancelAction']</value>
      <webElementGuid>8551e859-cc27-4345-a495-a3846ea5f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterContent']/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>7528452f-2f61-4fa4-a2f0-dfd4003436fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>6d368264-1a1a-4e31-8860-ed599af6e396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Time Log'])[2]/following::a[2]</value>
      <webElementGuid>3021f92a-175d-4c9b-bd40-1deea53ac599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[2]/following::a[2]</value>
      <webElementGuid>bc5eb64b-2f5c-4530-9112-769004d794e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Log Approving Person:'])[1]/preceding::a[1]</value>
      <webElementGuid>54fa2e45-aa37-4ea2-9994-fbb25bef8e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizwan Ul Ahmad Khan'])[1]/preceding::a[1]</value>
      <webElementGuid>94fa31a4-d61d-4e63-a1da-3b3c5998df8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>7f3d8217-4b19-4b9e-8474-52e30de69e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>2b08ac0a-a78e-4a2a-a1d1-16c146832f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>3ea6948b-014f-4842-9df3-f38f766fa636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'cancelAction' and @title = 'Cancel' and (text() = ' Cancel' or . = ' Cancel')]</value>
      <webElementGuid>1d656189-df35-4756-89bd-8efb0064357c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
