<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search_filter</name>
   <tag></tag>
   <elementGuidId>acf73866-b45f-40f4-8ff1-7468539f9ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnApplyAdvanceFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnApplyAdvanceFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a83ab2dd-46fd-4365-8a5f-ce5164c0a619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2b1f70ce-51a8-4b69-a53d-f01c25974576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnApplyAdvanceFilter</value>
      <webElementGuid>0ef54367-a453-43f3-b381-2f5cf1b2613c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryFilterAction</value>
      <webElementGuid>1b759c6c-48cd-49e4-9d00-2fdcfbe2c24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>09153c88-b6b1-4b2a-9f9c-201a03405811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnApplyAdvanceFilter&quot;)</value>
      <webElementGuid>77f4cb23-d8ba-4731-9766-1685ebc2eedf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnApplyAdvanceFilter']</value>
      <webElementGuid>c6ad8f27-bb46-49c2-b19d-14caee114de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancefilterOverlay']/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>0e08f446-8115-4438-be88-93ffd28cb05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Search')])[2]</value>
      <webElementGuid>90b14772-5e67-4119-80c0-c08962b8c4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[5]/following::a[3]</value>
      <webElementGuid>6c419982-ec5a-4433-bfa5-a87e4c9c622b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Status'])[1]/following::a[3]</value>
      <webElementGuid>d6604225-c851-461e-af08-465d10e28613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::a[2]</value>
      <webElementGuid>d27e924b-afa8-408a-b328-a39ba77e429a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='records'])[1]/preceding::a[2]</value>
      <webElementGuid>4cf0e9b8-f62c-4a3c-bf0e-5c34bde6520e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>2f9ded36-0a5f-4dd5-8a9d-fcc8bdffc087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>1f0d46fe-cd22-43f5-8d47-238110f1438a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a</value>
      <webElementGuid>c30e825b-9be4-4333-932b-951df1594411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btnApplyAdvanceFilter' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>022fe6b3-5446-446d-8e39-007aed86bd8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
