<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search_filter</name>
   <tag></tag>
   <elementGuidId>fe17bb32-862e-427d-b521-64aad729098a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnApplyAdvanceFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnApplyAdvanceFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2446684a-3443-4c8b-960b-36eaf6a1dce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a1b8a368-1fe4-4e8e-9d34-fe1342bca393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnApplyAdvanceFilter</value>
      <webElementGuid>5541d877-29c9-4f3d-8b8b-4570ae88b088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryFilterAction</value>
      <webElementGuid>814d0bef-f73f-48b5-b58a-79ebeb3c5af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>19f8c4ff-9474-41a3-b9ff-624afe3dd641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnApplyAdvanceFilter&quot;)</value>
      <webElementGuid>9299ea4f-49e1-4455-9e8c-e048d43cc092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnApplyAdvanceFilter']</value>
      <webElementGuid>de5696c2-0315-4e9c-9693-8e2f805af957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancefilterOverlay']/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>6d608736-0a45-41ed-be86-256a2593911c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Search')])[2]</value>
      <webElementGuid>036518ad-7397-4823-9090-3c31e2ed311d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[5]/following::a[3]</value>
      <webElementGuid>37aeb12c-59e3-43bd-81f6-0861df8da762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Status'])[1]/following::a[3]</value>
      <webElementGuid>63979b87-ee3d-4c4a-b7dc-0300c6aa391e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::a[2]</value>
      <webElementGuid>40d72933-4e75-48a8-93fb-0461eaddedc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='records'])[1]/preceding::a[2]</value>
      <webElementGuid>9f9f56fb-3266-4067-87b8-0c0908b89785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>475be2d2-1c17-466b-b2b5-6e2135ebd452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>25728a50-b175-4850-9563-ffc0b4a4c616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a</value>
      <webElementGuid>6f2f9146-5e26-434d-a466-62a7c7f4e8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btnApplyAdvanceFilter' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>636049d5-5cd9-4ff6-933e-9a0639c22d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
