<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>End Date_endDate_calendarButton</name>
   <tag></tag>
   <elementGuidId>c2587bef-8e5e-4eac-ba46-808d101fd225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endDate_calendarButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='endDate_calendarButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc66873c-80ab-4c09-8abe-7aa171e4c0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc041f0f-f7a2-4b18-8f5c-c322a8437540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4dae61e3-809a-4607-b98c-2c33d404df4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate_calendarButton</value>
      <webElementGuid>41472d24-021c-4de3-8080-997f6788158a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>95bc1792-7158-4f7e-b028-d748c480154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-button-common ui-unselectable ui-igedit-button-ltr ui-state-default ui-igedit-dropdown-button ui-igedit-buttonhover ui-state-hover</value>
      <webElementGuid>18b78fec-a419-45ec-a71a-27dfdcdf0484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show calendar</value>
      <webElementGuid>6fc89daa-572c-4cfc-bc0c-a93047789dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDate_calendarButton&quot;)</value>
      <webElementGuid>d5fca02e-f7ca-4b9c-b37a-ec57186ce491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='endDate_calendarButton']</value>
      <webElementGuid>4b7b43a4-c9bf-4cba-87d2-46d0fc7ac12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myTimeLogFilter']/div[2]/div/div/div/div</value>
      <webElementGuid>c612752d-01a7-4568-b9d5-0a972fddcd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::div[4]</value>
      <webElementGuid>b8bf6c1d-09a2-4d80-9b67-51c31a410769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[2]/following::div[5]</value>
      <webElementGuid>415570db-1a1d-42e2-a5e4-e6e5af85def0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[3]/preceding::div[3]</value>
      <webElementGuid>18fb6fce-ebf9-4510-97a3-dc21d215573d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Type'])[1]/preceding::div[5]</value>
      <webElementGuid>57a2ca4f-abc7-4241-9b44-d3b7acd3b04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>d1265976-bfff-4bb4-879a-6ef261e5ceac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'endDate_calendarButton' and @title = 'Show calendar']</value>
      <webElementGuid>ed771684-d7aa-4210-ac7e-1843fffa0be5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
