<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hover tab</name>
   <tag></tag>
   <elementGuidId>fe44bfbb-7410-46c9-b5de-3eaffe310a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myTimeLogFilter']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-igedit.ui-igedit-container.ui-widget.ui-corner-all.ui-state-default.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09371ab8-e3fc-4e19-a33b-817bbdd56ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit ui-igedit-container ui-widget ui-corner-all ui-state-default ui-state-hover</value>
      <webElementGuid>01c5b52d-7907-46e2-a26b-9bb4245d87e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTimeLogFilter&quot;)/div[@class=&quot;col-lg-6 col-md-12 col-sm-12 col-xs-12 form-group&quot;]/div[1]/div[@class=&quot;ssi-time-picker&quot;]/div[@class=&quot;ui-igedit ui-igedit-container ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]</value>
      <webElementGuid>4aeb3dc9-ba35-488d-b5f9-39d39358bedf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myTimeLogFilter']/div/div/div/div</value>
      <webElementGuid>05adbb40-d3f2-4117-9004-b3937966d0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/following::div[3]</value>
      <webElementGuid>9d6813b5-c226-4b76-a03b-85f678244be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[8]</value>
      <webElementGuid>93c8c6eb-58d0-45d0-badb-83fcd31b80a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[2]/preceding::div[4]</value>
      <webElementGuid>55fe07c5-5c69-439f-85ab-c4b29bd89bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/preceding::div[6]</value>
      <webElementGuid>e915fc03-dd68-42fb-846a-88ce625cd7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div/div/div/div</value>
      <webElementGuid>91aa156f-4069-41f3-bb7b-2ae3b0870c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
