<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Date_fromDateID</name>
   <tag></tag>
   <elementGuidId>935e9cd4-7581-4c51-9760-b5fd34afbfef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromDateID']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fromDateID' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fromDateID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f133b2ea-7b46-47da-b866-59fa02f78ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromDateID</value>
      <webElementGuid>1786bb8c-ec62-4c21-94b0-89a67b08877a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input hasDatepicker ui-igvalidator-target</value>
      <webElementGuid>db6bc373-3f12-43db-a1ea-1410e31f8c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae0887d2-0b6a-4df0-96c4-c4605454843f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ebe6f3f7-2e77-4d73-bddf-08284d139e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>54074dac-ab1d-48a3-b0c4-cbe9de46acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Picker</value>
      <webElementGuid>f2987b6e-fb14-464e-aa0c-d1f96aaecc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromDateID&quot;)</value>
      <webElementGuid>28073d81-6441-4b3d-a3e3-ffe8d1278653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromDateID']</value>
      <webElementGuid>6d2ccfc4-8e1e-48aa-bfa4-2cc3abbd11b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divValidationsFilter']/div/div/div/div[2]/input</value>
      <webElementGuid>f5895b4c-76e2-4a51-8e2b-7f2990e37963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a1d3ad65-7a0d-4345-b6a1-1c212111321b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
