<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__logTimeIn</name>
   <tag></tag>
   <elementGuidId>524b273d-5e73-4368-b8aa-8dea05b0c58f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logTimeIn1EditingInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logTimeIn1EditingInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b49c46f4-649a-47f1-8575-098fb10c9a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6b9e58c-3218-49b2-a2e0-d70b344079d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>f8e4d1d5-6b65-4c35-aa5d-b7d5f98fe505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeIn1EditingInput</value>
      <webElementGuid>ef44a2de-af71-4a77-b2b9-86ea285b3bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>108c670a-3483-4c61-ad14-9495cdc99cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>4185e1ea-1124-4ab7-b9e6-ec89467fd482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeIn1EditingInput&quot;)</value>
      <webElementGuid>5ad4d16b-390c-40ce-8ce2-b6bd6cea396f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logTimeIn1EditingInput']</value>
      <webElementGuid>ec5aaa12-41b4-406f-8c72-4a4953c3c834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logTimeIn1']/div[3]/input</value>
      <webElementGuid>d50c5007-23f9-4b1c-b9af-f4673f4346b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>43d4d75b-1c08-4645-b43d-decd97cadaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'logTimeIn1EditingInput']</value>
      <webElementGuid>cf5321bd-4821-4065-9d98-5ce1609474c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
