<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__logTimeOut</name>
   <tag></tag>
   <elementGuidId>9c401a3f-a022-49fa-ae3d-19a896b79e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logTimeOut1EditingInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logTimeOut1EditingInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5f0dcda-d88c-4885-b92b-2bd441a94195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fd68976-b889-4d30-b9a2-96648c341085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>c8770356-d4fe-4381-9f99-19011adf8f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeOut1EditingInput</value>
      <webElementGuid>d8776223-602a-42b6-80c3-a751d9654a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>acf45aef-8261-45f9-b39d-01ae4c5ce24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>be9dbc43-7269-4422-837a-433a5a982a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeOut1EditingInput&quot;)</value>
      <webElementGuid>5a5a4c0f-59d2-4b93-94ef-6a3c5da0a9d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logTimeOut1EditingInput']</value>
      <webElementGuid>286e18d7-da60-477e-b28b-661af73c1419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logTimeOut1']/div[3]/input</value>
      <webElementGuid>e4efeb99-eb7b-4753-84e2-1020475fb676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/input</value>
      <webElementGuid>1d39929f-1cb7-4d11-bbe7-53a18228791c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'logTimeOut1EditingInput']</value>
      <webElementGuid>e1a70bac-7703-4ee7-95ad-ea36a3b87e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
