<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__logTimeOut</name>
   <tag></tag>
   <elementGuidId>71a819c0-7131-4c6b-accb-88c913baacb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logTimeOut1EditingInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logTimeOut1EditingInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df8f7ff6-d11e-4ced-91f0-192dfc0998ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9590a145-82eb-4c5f-b5cd-dbd22601a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>ead310cc-cd9b-41a6-826d-46d456e0dfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeOut1EditingInput</value>
      <webElementGuid>ff8a90e4-d6e8-43c7-a424-ddd7e2233ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fd6de6a8-34ab-4ce4-9a2b-81d23eed3473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>2c5be893-e73c-4d68-a527-bb59559cb6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeOut1EditingInput&quot;)</value>
      <webElementGuid>b430b5ea-8e6b-4114-b20a-5ebc68cf8a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logTimeOut1EditingInput']</value>
      <webElementGuid>18d841b9-e765-45e7-9c95-0875a15531e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logTimeOut1']/div[3]/input</value>
      <webElementGuid>35d92a71-bbe4-4b80-875a-ae6b49e369fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/input</value>
      <webElementGuid>4b4a1163-0f02-4dcc-867e-1eadc136d408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'logTimeOut1EditingInput']</value>
      <webElementGuid>8dec122f-83a6-4010-aa20-cab7022bd9b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
