<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Date_fromDateID</name>
   <tag></tag>
   <elementGuidId>553783a9-1ba4-469b-8b45-3a2795805616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromDateID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromDateID']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fromDateID' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87a9f9cb-9543-4692-9310-427091048356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromDateID</value>
      <webElementGuid>8e74fba3-d85c-46de-8539-974bbf2ee8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input hasDatepicker ui-igvalidator-target</value>
      <webElementGuid>a17878bb-7f0a-46fa-bb97-a6230c78efb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66cfe6af-5264-4673-abb2-10d08c7dceaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6435b55a-eedd-49c9-866b-b9d1761f0d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>16d15048-7959-4a12-ab51-ac73325f5d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Picker</value>
      <webElementGuid>f4330590-fde5-4c8e-a276-2ec4802105c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromDateID&quot;)</value>
      <webElementGuid>66ebccd9-6496-46df-95b7-a2bc5a71d9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromDateID']</value>
      <webElementGuid>aed3bd02-1624-4bdf-9d9d-e366927cba6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divValidationsFilter']/div/div/div/div[2]/input</value>
      <webElementGuid>7d8c1af3-f92e-452a-ad96-208eed65cf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a8bbf09a-0620-4782-bb41-82217f82b493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
