<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To Date_toDateID</name>
   <tag></tag>
   <elementGuidId>d754f6b9-4694-42ca-b4bb-20bcce8850a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toDateID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='toDateID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d58b0c4-0c6b-47ef-9eb6-eb152a061fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toDateID</value>
      <webElementGuid>a783ec86-3059-4a09-b7ed-b66591ffe431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input hasDatepicker ui-igvalidator-target</value>
      <webElementGuid>d61590ae-6ac3-40b2-a585-2974e90a2dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8bc65f8-d9c6-4bc1-b5b4-1024f10ddc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ea9e0a72-599c-43c9-88c2-e90edd07c4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>09e7aa17-9f4a-40f6-8798-9f65fb9f2bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Picker</value>
      <webElementGuid>2d830b88-6414-4ee6-99b1-01a655750507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toDateID&quot;)</value>
      <webElementGuid>7e4122ad-036a-4cf3-83e6-452ab1ce7d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='toDateID']</value>
      <webElementGuid>0d38d92b-5337-463c-94fe-04798e18c87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divValidationsFilter']/div[2]/div/div/div[2]/input</value>
      <webElementGuid>74c1870a-2503-4100-b523-b9ae2446b69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>ba0915ac-db3e-4259-9258-7e4839811b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
