<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selected_End Date_ui-igedit ui-igedit-container ui-widget ui-corner-all ui-state-default ui-state-focus ui-state-hover</name>
   <tag></tag>
   <elementGuidId>8f103338-361b-47c5-9c8c-affa576a10f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-igedit.ui-igedit-container.ui-widget.ui-corner-all.ui-state-default.ui-state-focus.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myTimeLogFilter']/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f2fb725-a920-4d99-8b8b-e72142b84991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit ui-igedit-container ui-widget ui-corner-all ui-state-default ui-state-focus ui-state-hover</value>
      <webElementGuid>aa88afed-cbce-44fd-ac4f-3917f6fd31e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTimeLogFilter&quot;)/div[@class=&quot;col-lg-6 col-md-12 col-sm-12 col-xs-12 form-group&quot;]/div[1]/div[@class=&quot;ssi-time-picker&quot;]/div[@class=&quot;ui-igedit ui-igedit-container ui-widget ui-corner-all ui-state-default ui-state-focus ui-state-hover&quot;]</value>
      <webElementGuid>d9e2dc8c-6e70-44ac-a418-b58f15f3c5ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myTimeLogFilter']/div[2]/div/div/div</value>
      <webElementGuid>f5a6f5f5-a550-4d46-8d70-b7fe02df810a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::div[3]</value>
      <webElementGuid>13742abc-cdc9-4a0e-a2da-8474ce17d016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[2]/following::div[4]</value>
      <webElementGuid>a746d059-7738-48b2-aef4-e6c8d4935245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[3]/preceding::div[4]</value>
      <webElementGuid>3c16f661-41b8-40f3-8536-9afdd0f9690a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Type'])[1]/preceding::div[6]</value>
      <webElementGuid>9bea79c9-2db9-49c9-b1fa-75118455f68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>6f9bdd8c-1d09-4901-b9c6-bcff5e042a67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
