<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Start Date_startDate_calendarButton</name>
   <tag></tag>
   <elementGuidId>83d9d6c3-8c8b-4b87-975e-53aaa6a02270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDate_calendarButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='startDate_calendarButton']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ui-datepicker-div&quot;]/table[count(. | //*[@id = 'startDate_calendarButton' and @class = 'ui-igedit-button-common ui-unselectable ui-igedit-button-ltr ui-state-default ui-igedit-dropdown-button ui-igedit-buttonhover ui-state-hover']) = count(//*[@id = 'startDate_calendarButton' and @class = 'ui-igedit-button-common ui-unselectable ui-igedit-button-ltr ui-state-default ui-igedit-dropdown-button ui-igedit-buttonhover ui-state-hover'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0676fb5e-6173-4b30-a177-7e045ff189db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c643de1-4c35-441a-be53-9f80aa7a4c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3e42102b-eafb-47b5-815b-3bb80a19a4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate_calendarButton</value>
      <webElementGuid>2c7e3b0c-71d6-4bfb-8c0d-051e1d15384a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>7da3ebb4-2f47-4b75-bed6-633d1b38045e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-button-common ui-unselectable ui-igedit-button-ltr ui-state-default ui-igedit-dropdown-button ui-igedit-buttonhover ui-state-hover</value>
      <webElementGuid>f00e6b50-0531-462c-98b4-4d9a318608d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show calendar</value>
      <webElementGuid>3366ed41-768c-47f6-a37d-101b7df29a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ui-datepicker-div&quot;]/table</value>
      <webElementGuid>9df49224-b1f5-4133-95c6-e8cf9593bcd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='startDate_calendarButton']</value>
      <webElementGuid>3b6a7e1b-4c93-4c24-b425-f01e43b0cc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myTimeLogFilter']/div/div/div/div/div</value>
      <webElementGuid>8d6f8c26-d12a-42b3-ada4-53eeb1bac066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/following::div[4]</value>
      <webElementGuid>dfc39a52-fbbd-4c0d-b61c-42329c30adac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[9]</value>
      <webElementGuid>2463e6d8-6074-4c64-a443-f9c7f0e09e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[2]/preceding::div[3]</value>
      <webElementGuid>9eff2def-c1c3-415f-86af-42a4f661d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/preceding::div[5]</value>
      <webElementGuid>34a7756a-ddb7-4d5e-b863-f27b3e8da1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div/div/div/div/div</value>
      <webElementGuid>ba4cba10-d169-4bc6-8553-dc22afa4ea4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'startDate_calendarButton' and @title = 'Show calendar']</value>
      <webElementGuid>6c42da48-1d87-47f7-9a80-ba747f294f42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
