<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_sidemenu-burgermenu</name>
   <tag></tag>
   <elementGuidId>1fad16d4-b16e-405d-8d5e-a70a1288c4e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '#')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.icon.icon-burgermenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7581a82a-cfe8-438a-98b8-7469ae96ba3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-burgermenu</value>
      <webElementGuid>1787f273-d65b-4883-bf48-871d63653d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>139682f7-8b5a-4a2b-a8c0-63f373c8e237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;@*@currentActiveAreaClass*@&quot;]/div[@class=&quot;wrapper&quot;]/div[1]/div[@class=&quot;menu-header header&quot;]/div[@class=&quot;top-header-fixed&quot;]/div[@class=&quot;right-menu&quot;]/div[@class=&quot;top-nav&quot;]/ul[1]/li[1]/a[@class=&quot;icon icon-burgermenu&quot;]</value>
      <webElementGuid>bbba52e2-152b-4590-ab94-24860040651e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>053acafc-37c3-425b-a0b1-049908f154c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d2d2dc7c-5d25-4bec-8305-3365d2af0203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>0f831870-a77a-4cae-9066-a98cd9fe8592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
