<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Time Out</name>
   <tag></tag>
   <elementGuidId>834a877c-723b-4552-a848-f8fb6c38dbc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='log1']/div[2]/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c220b119-3e01-4fc3-b2c5-e23571e1f59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>15d9326a-7122-4cd9-8742-03e3aed49724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time Out*</value>
      <webElementGuid>ab318935-8aa0-4a36-8b9e-1920106b1d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;log1&quot;)/div[@class=&quot;detail-holder&quot;]/div[@class=&quot;control-holder&quot;]/label[@class=&quot;control-label&quot;]</value>
      <webElementGuid>cd022c21-b37d-4ce0-a167-44d2acc4b0e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='log1']/div[2]/div[3]/label</value>
      <webElementGuid>02581181-9db4-4df5-a23f-9f5a9daff025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>daad428e-56a2-4e65-9946-7c6601fee340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2022'])[1]/preceding::label[1]</value>
      <webElementGuid>b43a22cf-db50-4c9a-8695-75d1b3640a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time Out']/parent::*</value>
      <webElementGuid>d01cf84b-2889-4ffc-8130-ecec7c50ce2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>634a67b0-1a33-4962-b6d6-da2ff32fe5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Time Out*' or . = 'Time Out*')]</value>
      <webElementGuid>69e1917c-bdbe-4680-a241-815acb1c4374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
