<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>open_detail_search</name>
   <tag></tag>
   <elementGuidId>66843a22-e7ac-4a95-92f0-f828cf875b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ssi-icon-moreArrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAdvanceFilter']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;btnAdvanceFilter&quot;)/span[@class=&quot;ssi-icon-moreArrow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a63979fa-e644-4b88-b599-8db21930eb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssi-icon-moreArrow</value>
      <webElementGuid>5daedc1c-170a-48f8-9721-ef209924244d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAdvanceFilter&quot;)/span[@class=&quot;ssi-icon-moreArrow&quot;]</value>
      <webElementGuid>882ac70c-5cf1-4e5d-af51-130153245cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btnAdvanceFilter']/span</value>
      <webElementGuid>0822b2f7-49b6-48a9-b085-67bc28bd4c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::span[1]</value>
      <webElementGuid>b98852b4-94fb-40ab-a826-e8a909a7176d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validations Runs'])[3]/following::span[3]</value>
      <webElementGuid>d34b28f8-d0ac-48b9-8132-8f43c275e027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date'])[1]/preceding::span[1]</value>
      <webElementGuid>a59384d6-c329-473d-a766-ef7ce945b4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[2]/preceding::span[1]</value>
      <webElementGuid>92aaecd1-1462-4689-bb49-b850c265adcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>90cf0c86-8555-48ea-8fad-35525eeb87db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
